package gr.fellow.fellow_traveller.utils

const val PREFS_AUTH_TOKEN = "SESSION"
const val key = "AIzaSyBJ8UG-fR3GSjfbfAcatZezGZi2Y8FDzqA"
const val language = "el"
const val components = "country:gr"

const val ACCESS_DENIED = 50
const val SOMETHING_WORNG = 60
const val INTERNET_ERROR = -10

// AUTH
const val AUTH_LOGIN_WRONG_FIELDS = 100
const val AUTH_PASSWORD_ARE_THE_SAME = 101
const val AUTH_PASSWORD_ICORRECT = 102
const val AUTH_CHECK_ALREADY_EXIST = 103

// USER
const val USER_PHONE_EXIST = 200
const val USER_EMAIL_EXIST = 201
const val USER_NOT_FOUND = 202

// CAR
const val CAR_NUMBER_PLATE_EXIST = 300
const val CAR_NOT_BELONG_TO_USER = 301

// TRIP
const val TRIP_NOT_FOUND_OR_NO_ACTIVE = 400
const val TRIP_USER_NOT_FOUND = 401
const val TRIP_CAR_NOT_BELONG_TO_USER = 402
const val TRIP_USER_ALREADY_PASSENGER = 403
const val TRIP_USER_IS_CREATOR = 404
const val TRIP_NOT_AVAILABLE_SEATS = 405
const val TRIP_NOT_AVAILABLE_LUGGAGE = 406
const val TRIP_CHECK_PET_ACCEPTS = 407
const val TRIP_USER_IS_NOT_CREATOR = 408
const val TRIP_TIMESTAMP_INCORRECT = 409
const val TRIP_PICKUP_POINT = 410
const val TRIP_USER_NOT_PASSENGER = 411
const val TRIP_QRCODE_EARLY = 412
const val TRIP_QRCODE_WRONG = 413

// REVIEW
const val REVIEW_YOURSELF = 501
const val REVIEW_USER_TARGET_NOT_FOUND = 502
const val REVIEW_HAS_ALREADY_REGISTERED = 503
const val REVIEW_TIMESTAMP_INCORRECT = 504

// NOTIFICATION
const val NOTIFICATION_NOT_BELONGS_TO_THIS_USER = 600
